# https://hub.docker.com/_/python?tab=tags

## Example1 - Basic Fetch & Run
#FROM python:3.8.5-alpine3.12
#ENTRYPOINT ["python3"]


## Example2 - Copy code & Test
#COPY src/ /
#CMD ["/hello-vertiv.py"]


## Example 3 - Install packages & Debug container
#RUN apk --no-cache --virtual add bash \
#	&& pip3 install --no-cache-dir 'redis==3.4.1'
#ENTRYPOINT ["/bin/bash"]

