# https://hub.docker.com/_/golang?tab=tags

## Example1 - Go build
#FROM golang:1.15rc1-alpine3.12
#WORKDIR /app
#COPY src/ /app
#RUN go build -o /hello-vertiv hello-vertiv.go
#ENTRYPOINT ["/hello-vertiv"]


## Example2 - Install python3
#RUN apk --no-cache add python3
#ENTRYPOINT ["python3"]
#CMD ["--version"]


## Example3 - Install & clean build tools
#RUN apk --no-cache --virtual .build-deps add git build-base \
#	&& gcc -v \
#	&& apk del .build-deps

