name: Dockerfile Templates

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    
env:
  IMAGE_NAME: dockerfile-templates

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup access to other repos
      run: |
        #https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
        #https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
        git config --global url."https://eric-zaluzec-vertiv:${{ secrets.CI }}@github.com".insteadOf "https://github.com"

    - name: Build the API Gateway Docker image
      run: docker build . --file Dockerfile --tag dockerfile-templates

    - name: Log into GitHub's Docker registry
      run: echo "${{ secrets.CI }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      
    - name: Push image to GitHub's Docker registry
      run: |
        IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        
        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest
        
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        
        docker tag dockerfile-templates $IMAGE_ID:$VERSION
        
        # Container run test
        docker run dockerfile-templates
        
        docker push $IMAGE_ID:$VERSION   